### ISSUE TITLE
Event subscriber exit after device server restart on Windows

### ISSUE THREAD

**Issue by liujin001** [tango-controls/cppTango#501] opened 2018-11-24 15:34 UTC
I test libtango_9.3.3_v140_x64.zip (download from https://ci.appveyor.com/project/bourtemb/cpptango-tt3w8/branch/tango-9-lts ) on Windows 10 and Visual Studio Community 2015.

1. start TangoTest/test server, config sys/tg_test/1 device's long_scalar attribute Periodic event
2. start event subscriber(EventSub.exe  
[EventSub.cpp.zip](https://github.com/tango-controls/cppTango/files/2612375/EventSub.cpp.zip)
)
3. shut down TangoTest/test server(Ctrl+c), and re-run TangoTest/test server instantly
4. EventSub.exe report API_EventTimeout exception one or two times, then exit

but i test this on CentOS7(tango-9.2.5a),  event subscriber will not exit, after TangoTest/test restart, subscriber receive event normally.

**Comment by bourtemb** [comment] 2018-11-27 16:45
Hi @liujin001 

I'm sorry but I didn't manage to reproduce the error you encountered. In my environment, EventSub.exe does not exit when I restart TangoTest and reconnects well.
Is it systematically reproducible in your case?
If yes, could you give more details about your configuration?
Are TangoTest.exe and EventSub.exe running on the same host/same OS in your case?
Are they both using libtango_9.3.3_v140_x64 version?
What is your long_scalar periodic event period? What is long_scalar attribute polling period?
Sorry to ask this question, but are you sure the EventSubscriber didn't exit on Windows simply because the 10 minutes of the tests were expired?
Can you check the return code of EventSub.exe to see whether it is EXIT_FAILURE or EXIT_SUCCESS?
Could you provide the log of the messages displayed on the console?
Thanks in advance for your answers.

**Comment by liujin001** [comment] 2018-11-30 05:38
Hi bourtemb

It's maybe my Win10 Virtual Machine problem,  because if i run TangoTest.exe and EventSub.exe on Win10 Physical Machine, it not reproduce this problem.

My VM test environment information:
1. build TangoTest.exe and EventSub.exe all with libtango_9.3.3_v140_x64
2. run TangoTest.exe and EventSub.exe on one Win10 Virtual Machine.
3. long_scalar periodic event period is 1000ms
4. i am sure EventSub.exe not exit on Windows simply because the 10 minutes of the tests were expired

I will check my VM config, then may give more information.

**Comment by bourtemb** [comment] 2019-03-01 13:34
@liujin001, any update on this issue?

**Comment by t-b** [comment] 2020-10-20 20:05
Closing as it the OP could not reproduce the problem. Please reopen if you have any news.

**Closed by t-b** 2020-10-20 20:05 UTC
Labels: Windows, question
